version: "3.7"

services:
  build-img:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64/v8"
    dns:
      - 192.168.33.7
    image: mmhk/html2pdf:chromedp
  
  app:
    image: mmhk/html2pdf:chromedp
    restart: always
    environment:
      - LISTEN=0.0.0.0:4444
      - WEB_ROOT=/app/web_root
      - TIMEOUT=60
      - CHROME_PATH=/headless-shell/headless-shell
      - LOG_LEVEL=INFO
      - TZ=Asia/Hong_Kong
    ports:
      - 4444:4444